[package]
name = "stoop-swc-compiler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
swc_core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }


[profile.release]
lto = true
opt-level = 3
